cat <<EOF > aws-auth.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::570430250751:role/default-eks-node-group-20251205033034584900000005
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

  mapUsers: |
    - userarn: arn:aws:iam::570430250751:user/theareak-ecr-deployer
      username: terraform-admin
      groups:
        - system:masters
EOF
